# Lets run on the new infrastructure
sudo: false

# We're having issues on the default Trusty setup, lets wait for now
dist: precise

language: python
python: 3.6

install:
  - pip install tox codecov coveralls

# defaults:
#   - &main_test_script
#     before_script:
#     # Make a MariaDB database
#     # Fix wierdness with MariaDB on Travis - https://github.com/mozilla/kitsune/pull/2453/commits/229db28973f00dfc4fa7b386f266caf3417966a0
#       - if [[ $DB == mariadb ]]; then ./scripts/prep_mysql.sh ; fi
#       - if [[ $SEARCH == elastic ]]; then sudo service elasticsearch start && sleep 10; fi
#     # Make a posgres database
#       - if [[ $DB == postgres* ]]; then ./scripts/prep_psql.sh; fi

#     script:
#       - |
#         case "$DB" in
#           mariadb) export DATABASE_URL=mysql://travis:@localhost:3306/aristotle_test_db;;
#         postgres) export DATABASE_URL=postgresql://postgres:@localhost/aristotle_test_db;;
#           sqlite) export DATABASE_URL=sqlite:///./db.db;;
#                 *) export DATABASE_URL=sqlite:///./db.db;;
#         esac
#         echo "Running script with DATABASE_URL="$DATABASE_URL
#         echo "Running script with DB="$DB
#         echo $TRAVIS_BRANCH
#         echo "HEAD to TRAVIS_BRANCH"
#         git diff --name-only HEAD...$TRAVIS_BRANCH
#         echo "TRAVIS_BRANCH to HEAD"
#         git diff --name-only $TRAVIS_BRANCH...HEAD
#         ./scripts/tox_if.sh $MODULE dj$DJANGO_VERSION-test-linux-db-$DB-search-$SEARCH
#     services:
#       - postgresql
#       - redis-server
#       - elasticsearch
#       - mariadb
#     addons:
#       apt:
#         sources:
#           - elasticsearch-2.x
#         packages:
#           - elasticsearch
#       code_climate:
#         repo_token: ac63d774ebdd641ef502acf1588b36248726a28a50e4e1f4ba4295a157477f54
#       mariadb: '10.1'

#   - &main_test_script_py36
#       python: 3.6
#       <<: *main_test_script

#   - &test_accessibility_py36
#     stage: accessibility
#     python: 3.6
#     script: ./scripts/tox_if.sh $MODULE ally-$ALLY

jobs:

  include:
  #   - stage: stylecheck
  #     python: 3.6
  #     env: MODULE=aristotle-metadata-registry
  #     script: cd $TRAVIS_BUILD_DIR/python/$MODULE && tox -e flake8 --skip-missing-interpreters

  #   - stage: documentation
  #     python: 3.6
  #     env: MODULE=aristotle-metadata-registry
  #     script: ./scripts/tox_if.sh $MODULE docs

  #   - stage: testing-aristotle-mdr
  #     env: DJANGO_VERSION='1.11'  DB=sqlite  SEARCH=elastic MODULE=aristotle-metadata-registry
  #     <<: *main_test_script_py36
  #   - stage: testing-aristotle-mdr
  #     env: DJANGO_VERSION='1.11'  DB=postgres  SEARCH=elastic MODULE=aristotle-metadata-registry
  #     <<: *main_test_script_py36
  #   - stage: testing-aristotle-mdr
  #     env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=whoosh MODULE=aristotle-metadata-registry
  #     <<: *main_test_script_py36
  #   - stage: testing-aristotle-mdr
  #     env: DJANGO_VERSION='1.11'  DB=postgres  SEARCH=whoosh MODULE=aristotle-metadata-registry
  #     <<: *main_test_script_py36
  #   - stage: testing-aristotle-mdr
  #     env: DJANGO_VERSION='1.11'  DB=mariadb   SEARCH=whoosh MODULE=aristotle-metadata-registry
  #     <<: *main_test_script_py36
  #   - stage: testing-aristotle-mdr
  #     env: DJANGO_VERSION='1.11'  DB=mariadb   SEARCH=elastic MODULE=aristotle-metadata-registry
  #     <<: *main_test_script_py36

  #     # Possible failures:
  #   # - stage: testing
  #   #   env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=whoosh   VARIANT=haystack
  #   #   <<: *main_test_script_py36
  #   # - stage: testing
  #   #   env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=elastic  VARIANT=haystack
  #   #   <<: *main_test_script_py36

  #   - stage: testing-modules
  #     env: DJANGO_VERSION='1.11'  DB=postgres   SEARCH=elastic MODULE=aristotle-dataset-extensions
  #     <<: *main_test_script_py36

  #   - stage: testing-modules
  #     env: DJANGO_VERSION='1.11'  DB=postgres   SEARCH=elastic MODULE=comet-indicator-registry
  #     <<: *main_test_script_py36

  #   - stage: testing-modules
  #     env: DJANGO_VERSION='1.11'  DB=postgres   SEARCH=elastic MODULE=aristotle-pdf-downloads
  #     <<: *main_test_script_py36

  #   - stage: testing-modules
  #     env: DJANGO_VERSION='1.11'  DB=postgres   SEARCH=elastic MODULE=aristotle-mdr-graphql
  #     <<: *main_test_script_py36

  # # Test Accessibility
  #   - <<: *test_accessibility_py36
  #     env: ALLY=metadata_item MODULE=aristotle-metadata-registry
  #   - <<: *test_accessibility_py36
  #     env: ALLY=metadata_action MODULE=aristotle-metadata-registry
  #   - <<: *test_accessibility_py36
  #     env: ALLY=static MODULE=aristotle-metadata-registry

  # allow_failures:
    # - env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=whoosh   VARIANT=haystack
    # - env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=elastic  VARIANT=haystack
    
    # - stage: deploy
    #   script: true
    #   deploy:
    #       provider: pypi
    #       user: Samuel.Spencer
    #       skip_upload_docs: true
    #       password:
    #         secure: fNL+70u1QPgkC3+6iLSPBBeo/J1VrwVn6Tg9PdKR3n4X/m6MgAboDc93CfccfsxVxGqsIRBtEfUwRCJ6MrajWqgfQhjQ9KodiYzPVS8vPUQyOtn73AB8iPYKgKX1pFn6UVXcnI67RmtPyJJEUFPbqy5saKZfRpjVRH3vjM2mDJ0=
    #       on:
    #         branch: master
    #         distributions: sdist bdist_wheel
    #         repo: aristotle-mdr/aristotle-metadata-registry

    - stage: deploy-it
      script: true
      install: skip
      after_success: true
      deploy:
        provider: pypi
        user: Samuel.Spencer
        password:
          secure: "B3jQGTCMrCxXAIPE0gcQRVcyZeFVaWh3rTyYtTz6iKrHsj65pNFIFb8DNAK8MWmPms3U5tP0xQiReoGpoMZzxLPNRKZJCUIg2KccN3GjIzuz82tJZ59dFCt3cBxObX3HMFwuHjTqheW90zHVeyGUJv2LnV2iJfWuMKFnInFwATw="
        server: https://test.pypi.org/legacy/
        # skip_upload_docs: true
        on:
          all_branches: true
        distributions: sdist bdist_wheel
        repo: aristotle-mdr/aristotle-metadata-registry

after_success:
  - ./scripts/coverage_reporter.sh $MODULE

