# Lets run on the new infrastructure
sudo: false

# We're having issues on the default Trusty setup, lets wait for now
dist: precise

language: python

install:
  - pip install tox codecov coveralls

defaults:
  - &main_test_script
    stage: testing
    before_script:
    # Make a MariaDB database
    # Fix wierdness with MariaDB on Travis - https://github.com/mozilla/kitsune/pull/2453/commits/229db28973f00dfc4fa7b386f266caf3417966a0  
      - if [[ $DB == mariadb ]]; then ./aristotle_mdr/tests/bin/prep_mysql.sh ; fi
      - if [[ $SEARCH == elasticsearch ]]; then sleep 10; fi
    # Make a posgres database
      - if [[ $DB == postgres* ]]; then ./aristotle_mdr/tests/bin/prep_psql.sh; fi

    script:
      - |
        case "$DB" in
            mariadb) DATABASE_URL=mysql://travis:@localhost:3306/aristotle_test_db;;
         postgresql) DATABASE_URL=postgresql://postgres:@localhost/aristotle_test_db;;
             sqlite) DATABASE_URL=sqlite:///./db.db;;
                  *) DATABASE_URL=sqlite:///./db.db;;
        esac
        echo "Running script with DATABASE_URL="$DATABASE_URL
        echo "Running script with DB="$DB
        tox -e dj$DJANGO_VERSION-test-linux-db-$DB-search-$SEARCH --skip-missing-interpreters
    services:
      - postgresql
      - redis-server
      - elasticsearch
      - mariadb
    addons:
      apt:
        sources:
          - elasticsearch-2.x
        packages:
          - elasticsearch
      code_climate:
        repo_token: ac63d774ebdd641ef502acf1588b36248726a28a50e4e1f4ba4295a157477f54
      mariadb: '10.1'

  - &main_test_script_py27
      python: 2.7
      <<: *main_test_script

  - &main_test_script_py35
      python: 3.5
      <<: *main_test_script

jobs:
  allow_failures:
    - env: DJANGO_VERSION='1.8'  DB=sqlite    SEARCH=whoosh   VARIANT=haystack
    - env: DJANGO_VERSION='1.8'  DB=sqlite    SEARCH=elastic  VARIANT=haystack
    - env: DJANGO_VERSION='1.11' DB=sqlite    SEARCH=whoosh

  include:
    - stage: stylecheck
      python: 3.5
      script: tox -e pep8 --skip-missing-interpreters

    - stage: documentation
      python: 3.5
      script: tox -e docs --skip-missing-interpreters

    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=postgres  SEARCH=elastic
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=postgres  SEARCH=elastic
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=sqlite    SEARCH=whoosh
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=postgres  SEARCH=whoosh
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=mariadb   SEARCH=whoosh
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=mariadb   SEARCH=elastic

    - <<: *main_test_script_py27
      env: DJANGO_VERSION='1.8'  DB=postgres  SEARCH=elastic
    - <<: *main_test_script_py27
      env: DJANGO_VERSION='1.8'  DB=postgres  SEARCH=elastic
    - <<: *main_test_script_py27
      env: DJANGO_VERSION='1.8'  DB=sqlite    SEARCH=whoosh
    - <<: *main_test_script_py27
      env: DJANGO_VERSION='1.8'  DB=postgres  SEARCH=whoosh
    - <<: *main_test_script_py27
      env: DJANGO_VERSION='1.8'  DB=mariadb   SEARCH=whoosh
    - <<: *main_test_script_py27
      env: DJANGO_VERSION='1.8'  DB=mariadb   SEARCH=elastic

    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.10' DB=sqlite    SEARCH=elastic
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.10' DB=sqlite    SEARCH=whoosh
  # Possible failures:
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=sqlite    SEARCH=whoosh   VARIANT=haystack
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.8'  DB=sqlite    SEARCH=elastic  VARIANT=haystack
    - <<: *main_test_script_py35
      env: DJANGO_VERSION='1.11' DB=sqlite    SEARCH=whoosh

    - stage: accessibility
      python: 3.5
      script: tox -e ally-metadata_item --skip-missing-interpreters
      script: tox -e ally-metadata_action --skip-missing-interpreters
      script: tox -e ally-static --skip-missing-interpreters

    - stage: deploy
      script: true
      deploy:
        provider: pypi
        user: Samuel.Spencer
        skip_upload_docs: true
        password:
          secure: hJVN74vhyDjG22Ei5/gz0g0d/KfaW2kzjx85c3pT+4jmbTOC3OcGN7Exj+/2wEAygvQDmlijRGJ0yldL3IpE0+N7TASs0/6dNf8fMoG0zRTcuu1ywhUhSgqntRGMjRBpbXeVUeb6ydeAciDkrkmfyuGVQd6bXJQeCxcdU1X5iJ+mnbS9Lu1oUfXt6MZroMImwh+ZCvDn95e8QMFbSmO/3OE7CBtBiCaUMemlgzf1THJsw0JoO/GaU37NEjmsnt6xg8EcXRi/h+Pznnr+8LEs6gqcNRg8uS0mh3e6B3ynvovY6Pr8YdAazG6FTFezc3eQWjViQyBxHGbCcY1z0w7bATa+BT18k2/I6dfF6MFoitPtTmJ9tQEB1HOdL/ngJoYEa2TQxxsCal4qqCWNEgP6O5Jl7uK4u1y00wXQ1M3scGmP1kxu+4DWY9ywfnBvbF8SNKLd4qEkdxQIkZBYd7/4aU/3pHFVE1f+J7LSzLt8gIy/hnLCB23T/DEaLnQJDIBlP4Kcpb277vkayVjuRuGNfU5QXf29Sj4PKvXbVS9gtYDY8U5KheOhb7MmWTlq+WfGvyrpgLfasFQDjWGOqs4oJ4LDO4IJ6BG40LX/OozTXoiT1//DcwDU34SJQlfTiTidZMeOq1fdpQNG84Tig2MkuRnmvO8LF5uIS0I6G3GWP6U=
        on:
          branch: master
          distributions: sdist bdist_wheel
          repo: aristotle-mdr/aristotle-metadata-registry


after_success:
  - coveralls
  - codecov
